<script>
    let promise = new Promise((resolve,reject) => {
        setTimeout(() => reject(new Error("에러 발생")),1000)
    });

    promise.catch(alert);
</script>