<script>
    let promise = new Promise(function(resolve,reject){
        setTimeout(() => reject(new Error("에러 발생")),1000);
    });

    //reject 함수는 then의 두 번째 함수를 실행
    promise.then(
        result => alert(result), // 실행되지 않음
        error => alert(error) // 1초후 "Error : 에러 발생!"를 출력
    )
</script>